import { User } from '@/redux/slices/usersSlice'

export const users: User[] = [
  {
    id: 1,
    username: '',
    name: 'Шабашвили',
    second: 'Баховый',
    father: 'Тягович',
    age: 32,
    sex: 'male',
    city: 'Москва',
    role: 'frontend',
    phone: '+7-980-555-35-35',
    email: 'aaabbbaaa@gmail.com',
    events_count: 0,
    grade: 'middle'
  },
  {
    id: 2,
    username: '',
    name: 'Баранова',
    second: 'Анастасия',
    father: 'Адамовна',
    age: 42,
    sex: 'female',
    city: 'СПб',
    role: 'ux-ui',
    phone: '+7-981-345-67-78',
    email: 'opyatagaming@list.ru',
    events_count: 0,
    grade: 'middle'
  },
  {
    id: 3,
    username: '',
    name: 'Баранова',
    second: 'Анастасия',
    father: 'Адамовна',
    age: 42,
    sex: 'female',
    city: 'СПб',
    role: 'ux-ui',
    phone: '+7-981-345-67-78',
    email: 'opyatagaming@list.ru',
    events_count: 0,
    grade: 'middle'
  },
  {
    id: 4,
    username: '',
    name: 'Баранова',
    second: 'Анастасия',
    father: 'Адамовна',
    age: 42,
    sex: 'female',
    city: 'СПб',
    role: 'ux-ui',
    phone: '+7-981-345-67-78',
    email: 'opyatagaming@list.ru',
    events_count: 0,
    grade: 'middle'
  },
  {
    id: 5,
    username: '',
    name: 'Баранова',
    second: 'Анастасия',
    father: 'Адамовна',
    age: 42,
    sex: 'female',
    city: 'СПб',
    role: 'ux-ui',
    phone: '+7-981-345-67-78',
    email: 'opyatagaming@list.ru',
    events_count: 0,
    grade: 'middle'
  },
  {
    id: 6,
    username: '',
    name: 'Баранова',
    second: 'Анастасия',
    father: 'Адамовна',
    age: 42,
    sex: 'female',
    city: 'СПб',
    role: 'ux-ui',
    phone: '+7-981-345-67-78',
    email: 'opyatagaming@list.ru',
    events_count: 0,
    grade: 'middle'
  },
  {
    id: 7,
    username: '',
    name: 'Баранова',
    second: 'Анастасия',
    father: 'Адамовна',
    age: 42,
    sex: 'female',
    city: 'СПб',
    role: 'ux-ui',
    phone: '+7-981-345-67-78',
    email: 'opyatagaming@list.ru',
    events_count: 0,
    grade: 'middle'
  },
  {
    id: 8,
    username: '',
    name: 'Баранова',
    second: 'Анастасия',
    father: 'Адамовна',
    age: 42,
    sex: 'female',
    city: 'СПб',
    role: 'ux-ui',
    phone: '+7-981-345-67-78',
    email: 'opyatagaming@list.ru',
    events_count: 0,
    grade: 'middle'
  },
  {
    id: 0,
    username: '',
    name: 'Баранова',
    second: 'Анастасия',
    father: 'Адамовна',
    age: 42,
    sex: 'female',
    city: 'СПб',
    role: 'ux-ui',
    phone: '+7-981-345-67-78',
    email: 'opyatagaming@list.ru',
    events_count: 0,
    grade: 'middle'
  },
  {
    id: 10,
    username: '',
    name: 'Баранова',
    second: 'Анастасия',
    father: 'Адамовна',
    age: 42,
    sex: 'female',
    city: 'СПб',
    role: 'ux-ui',
    phone: '+7-981-345-67-78',
    email: 'opyatagaming@list.ru',
    events_count: 0,
    grade: 'middle'
  }
]